package com.skysoft.features.event.diana

internal object MythologicalRitualMobKey {
    const val KING_MINOS = "KING_MINOS"
    const val KING_MINOS_LS = "KING_MINOS_LS"
    const val MANTICORE = "MANTICORE"
    const val MANTICORE_LS = "MANTICORE_LS"
    const val MINOS_INQUISITOR = "MINOS_INQUISITOR"
    const val MINOS_INQUISITOR_LS = "MINOS_INQUISITOR_LS"
    const val SPHINX = "SPHINX"
    const val SPHINX_LS = "SPHINX_LS"
    const val MINOS_CHAMPION = "MINOS_CHAMPION"
    const val MINOTAUR = "MINOTAUR"
    const val GAIA_CONSTRUCT = "GAIA_CONSTRUCT"
    const val HARPY = "HARPY"
    const val CRETAN_BULL = "CRETAN_BULL"
    const val STRANDED_NYMPH = "STRANDED_NYMPH"
    const val SIAMESE_LYNXES = "SIAMESE_LYNXES"
    const val MINOS_HUNTER = "MINOS_HUNTER"
    const val TOTAL_MOBS = "TOTAL_MOBS"
}

internal object MythologicalRitualItemKey {
    const val CHIMERA = "CHIMERA"
    const val CHIMERA_LS = "CHIMERA_LS"
    const val DAEDALUS_STICK = "DAEDALUS_STICK"
    const val MINOS_RELIC = "MINOS_RELIC"
    const val MANTI_CORE = "MANTI_CORE"
    const val MANTI_CORE_LS = "MANTI_CORE_LS"
    const val FATEFUL_STINGER = "FATEFUL_STINGER"
    const val FATEFUL_STINGER_LS = "FATEFUL_STINGER_LS"
    const val SHIMMERING_WOOL = "SHIMMERING_WOOL"
    const val SHIMMERING_WOOL_LS = "SHIMMERING_WOOL_LS"
    const val BRAIN_FOOD = "BRAIN_FOOD"
    const val BRAIN_FOOD_LS = "BRAIN_FOOD_LS"
    const val KING_MINOS_SHARD = "KING_MINOS_SHARD"
    const val SPHINX_SHARD = "SPHINX_SHARD"
    const val MINOTAUR_SHARD = "MINOTAUR_SHARD"
    const val CRETAN_BULL_SHARD = "CRETAN_BULL_SHARD"
    const val HARPY_SHARD = "HARPY_SHARD"
    const val MYTHOS_FRAGMENT = "MYTHOS_FRAGMENT"
    const val CRETAN_URN = "CRETAN_URN"
    const val HILT_OF_REVELATIONS = "HILT_OF_REVELATIONS"
    const val GRIFFIN_FEATHER = "GRIFFIN_FEATHER"
    const val BRAIDED_GRIFFIN_FEATHER = "BRAIDED_GRIFFIN_FEATHER"
    const val MYTH_THE_FISH = "MYTH_THE_FISH"
    const val CROWN_OF_GREED = "CROWN_OF_GREED"
    const val MYTHOLOGICAL_DYE = "MYTHOLOGICAL_DYE"
    const val COINS = "COINS"
    const val TOTAL_BURROWS = "TOTAL_BURROWS"
}

internal object MythologicalRitualMagicFindKey {
    const val WOOL = "wool"
    const val CORE = "core"
    const val STINGER = "stinger"
    const val CHIMERA = "chimera"
    const val RELIC = "relic"
    const val FOOD = "food"
    const val STICK = "stick"
}
